### ISSUE TITLE
Crash on importing m3u8 playlists

### ISSUE THREAD

**Issue by wibblepegs** [jaylex32/Syncra#2]
I use musicbee to export playlists into m3u8 format . but have been unable to import any , export works fine.
Wont let me upload playlist files  her  so saved one as a txt file and uploaded.

Tried various playlists all cause a crash . Playlist is created but blank,
Its run locally on a windows 11 machine.
This sample playlist has a few odd character's but must dont 

Excellent work so far mate
[playlist.txt](https://github.com/user-attachments/files/17262238/playlist.txt)

**Comment by jaylex32** [comment]
Any error? When it crashes?

**Comment by jaylex32** [comment]
Does it give any kind of error? It seems like the format of the playlist is not formatted correctly. Plex is very picky, and if there's something incorrect, it will not work. Is there a reason that certain tracks in the playlist have a hard drive like "d:" and others in "D:"?

**Comment by wibblepegs** [comment]
No error messages , was getting a 500 error before as i was trying to import a m3u playlist not a m3u8.
No reason for the D d thats i can think off i didnt even spot that only reason i can think of is i do run fixlist the playlist repair program possible that uses capitals .

I will play around with a 1 track playlist see if that works and report back

**Comment by wibblepegs** [comment]
made a new 1 song playlist in musicbee still no luck .

got this  error ( i removed plex token bit of end of url)

Failed to import test.m3u. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:32400/playlists/upload?sectionID=16&path=C%3A%2FUsers%2FRonin%2FDocuments%2FExported+Playlists%2Ftest.m3u&X-

then on second attempt it crashed . perhaps its the musicbee export ?

**Comment by jaylex32** [comment]
> made a new 1 song playlist in musicbee still no luck .
> 
> got this error ( i removed plex token bit of end of url)
> 
> Failed to import test.m3u. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:32400/playlists/upload?sectionID=16&path=C%3A%2FUsers%2FRonin%2FDocuments%2FExported+Playlists%2Ftest.m3u&X-
> 

> then on second attempt it crashed . perhaps its the musicbee export ?


try this playlist, just remove the .txt and tell me if it works, this should work if you have your music in the D: drive and if your drive is D: ,

[playlist.m3u8.txt](https://github.com/user-attachments/files/17264602/playlist.m3u8.txt)

**Comment by wibblepegs** [comment]
Will do mate ,. Im in the middle of doing the plex dance ( remove and re-adding library) as i just spotted a possible directory path issue , may have been caused by a remote backup , path looks good on my end but different on the plex machine .

Will check and report back looking like an issue my end with correct path structure on plex machine

**Comment by jaylex32** [comment]
I will look into the ratings, but for now, this issue is resolved.
